repos:
  - repo: local
    hooks:
      - id: import-linter
        name: Check architecture boundaries
        entry: lint-imports
        language: system
        pass_filenames: false
        always_run: true