[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "data-analysis-gui"
version = "0.1.0"
description = "Patch-clamp electrophysiology data analysis GUI with MAT/CSV support"
authors = [
  { name="Charlie K.", email="your_email@example.com" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10"

dependencies = [
  "PySide6>=6.0.0",
  "matplotlib>=3.6",
  "numpy>=1.23",
  "pandas>=1.5",
  "scipy>=1.9"
]

[project.optional-dependencies]
test = [
  "pytest",
  "pytest-qt",
]

[project.scripts]
data-analysis-gui = "data_analysis_gui.main:run"

[tool.setuptools.packages.find]
where = ["src"]
include = ["data_analysis_gui*"]
