# .github/workflows/tests.yml
name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
      fail-fast: false  # Continue testing other combinations if one fails
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        # Install any macOS-specific dependencies if needed
        # Currently none required for this project
        echo "Setting up macOS environment"
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install additional test dependencies
      run: |
        pip install pytest pytest-xvfb
    
    - name: Run tests (macOS)
      if: runner.os == 'macOS'
      env:
        CI: true
        QT_QPA_PLATFORM: offscreen
        # macOS-specific environment variables if needed
      run: |
        pytest tests/ -v --tb=short -m "not gui and not ci_skip"
    
    - name: Run tests (Windows)
      if: runner.os == 'Windows'
      env:
        CI: true
        QT_QPA_PLATFORM: offscreen
      run: |
        pytest tests/ -v --tb=short -m "not gui and not ci_skip"
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.os }}-py${{ matrix.python-version }}
        path: test-results/